#!/bin/sh
### BEGIN INIT INFO
# Provides:          mobilizeds
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 5
# Default-Stop:      0 1 6
# Description:       MobilizeDS service
### END INIT INFO
 
SCRIPT="/usr/bin/hypnotoad /usr/local/mobilizeds/bin/mobilizeds"
RUNAS="root"
 
PIDFILE=/usr/local/mobilizeds/mobilizeds.pid
LOGFILE=/usr/local/mobilizeds/mobilizeds.log
 
status() {
  if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
    echo 'MobilizeDS service is not running' >&2
    return 3
  else
    echo 'MobilizeDS service is running' >&2
    return 0
  fi
}

start() {
  if [ -f "$PIDFILE" ] && kill -0 $(cat "$PIDFILE"); then
    echo 'Service already running' >&2
    return 1
  fi
  echo 'Starting service…' >&2
  local CMD="$SCRIPT &> \"$LOGFILE\" & echo \$!"
  su -c "$CMD" $RUNAS > /dev/null
  sleep 2;
  echo $(ps -ef  | grep mobilizeds | grep -v grep | awk '{ if( $3 == 1 ) { print $2; }}') > "$PIDFILE"
  echo 'Service started' >&2
}
 
stop() {
  if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
    echo 'Service not running' >&2
    return 1
  fi
  echo 'Stopping service…' >&2
  kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
  echo 'Service stopped' >&2
}
 
uninstall() {
  echo -n "Are you really sure you want to uninstall this service? That cannot be undone. [yes|No] "
  local SURE
  read SURE
  if [ "$SURE" = "yes" ]; then
    stop
    rm -f "$PIDFILE"
    echo "Notice: log file is not be removed: '$LOGFILE'" >&2
    update-rc.d -f mobilizeds remove
    rm -fv "$0"
  fi
}
 
case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status
    ;;
  uninstall)
    uninstall
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|uninstall}"
esac

